# Generated by Django 5.2.5 on 2025-11-22 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="User's message describing their feelings", validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(1000)])),
                ('sentiment_score', models.FloatField(help_text='Sentiment score from -1 (negative) to 1 (positive)')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('neutral', 'Neutral')], help_text='Detected primary emotion', max_length=20)),
                ('response', models.TextField(help_text='AI-generated supportive response')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this mood entry was created')),
                ('user', models.ForeignKey(help_text='User who created this mood entry', on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_moodent_user_id_54da3b_idx'), models.Index(fields=['emotion', '-timestamp'], name='api_moodent_emotion_a4da76_idx')],
            },
        ),
    ]
