# Generated by Django 5.2.5 on 2025-11-23 22:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_enabled', models.BooleanField(default=False, help_text='Whether daily reminders are enabled')),
                ('reminder_time', models.TimeField(default='09:00:00', help_text='Time for daily reminder')),
                ('notification_enabled', models.BooleanField(default=False, help_text='Whether browser notifications are enabled')),
                ('preferred_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', help_text='Preferred UI theme', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When preferences were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When preferences were last updated')),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='DailyMoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('neutral', 'Neutral')], help_text="User's selected emotion", max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note about the mood', max_length=500, null=True)),
                ('date', models.DateField(db_index=True, default=datetime.date.today, help_text='Date of the check-in')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this check-in was created')),
                ('user', models.ForeignKey(help_text='User who created this check-in', on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Mood Check-in',
                'verbose_name_plural': 'Daily Mood Check-ins',
                'ordering': ['-date', '-timestamp'],
                'indexes': [models.Index(fields=['user', '-date'], name='api_dailymo_user_id_b4503e_idx'), models.Index(fields=['user', '-timestamp'], name='api_dailymo_user_id_9ff118_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Goal title', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the goal', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('goal_type', models.CharField(choices=[('daily_checkin', 'Daily Check-in'), ('mood_improvement', 'Mood Improvement'), ('gratitude', 'Gratitude Journaling'), ('custom', 'Custom Goal')], default='custom', help_text='Type of goal', max_length=30)),
                ('target_value', models.IntegerField(help_text='Target value to achieve (e.g., number of days, entries)')),
                ('current_value', models.IntegerField(default=0, help_text='Current progress value')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='When the goal started')),
                ('target_date', models.DateField(help_text='Target completion date')),
                ('completed', models.BooleanField(default=False, help_text='Whether the goal has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this goal was created')),
                ('user', models.ForeignKey(help_text='User who created this goal', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_goal_user_id_00713a_idx'), models.Index(fields=['user', 'completed'], name='api_goal_user_id_eae8da_idx')],
            },
        ),
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='What the user is grateful for', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this entry was created')),
                ('user', models.ForeignKey(help_text='User who created this gratitude entry', on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratitude Entry',
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_gratitu_user_id_96b85d_idx'), models.Index(fields=['user', 'timestamp'], name='api_gratitu_user_id_9126a7_idx')],
            },
        ),
    ]
